apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m0s
  # secretRef:
  #   name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: podinfo
spec:
  imageRepositoryRef:
    name: podinfo
  # filterTags:
  #   ## use "pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'" if you copied the workflow example using github.run_number
  #   pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
  #   extract: '$ts'
  policy:
    semver:
      range: 5.0.x
    # numerical:
    #   order: asc
